apiVersion: apps/v1
kind: Deployment
metadata:
  name: deno-app-deployment
spec:
  replicas: 2  # Increase replicas
  selector:
    matchLabels:
      app: deno-app
  template:
    metadata:
      labels:
        app: deno-app
    spec:
      containers:
      - name: deno-app
        image: goodeesh/my-deno-app:local
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "1000m"
            memory: "256Mi"  # Increase memory request
          limits:
            cpu: "2000m"
            memory: "512Mi"    # Significantly increase memory limit
        ports:
        - containerPort: 8000
        startupProbe:        # Add startup probe
          httpGet:
            path: /health
            port: 8000
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:       # Add liveness probe
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20