apiVersion: v1
kind: Service
metadata:
  name: deno-app-service
spec:
  selector:
    app: deno-app
  ports:
  - protocol: TCP
    port: 8000 #this is the port where the service will run
    targetPort: 8000 # this is the port where the app runs
    nodePort: 32000
  type: NodePort
