apiVersion: apps/v1
kind: Deployment
metadata:
  name: bun-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bun-app
  template:
    metadata:
      labels:
        app: bun-app
    spec:
      containers:
      - name: bun-app
        image: goodeesh/my-bun-app:local
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "100m"  # Request 100 millicores
            memory: "128Mi"  # Request 128 MiB  
          limits:
            cpu: "500m"  # Max 500 millicores
            memory: "256Mi"  # Max 256 MiB
        ports:
        - containerPort: 5000
