apiVersion: apps/v1
kind: Deployment
metadata:
  name: bun-app-deployment
spec:
  replicas: 2  # Increase replicas
  selector:
    matchLabels:
      app: bun-app
  template:
    metadata:
      labels:
        app: bun-app
    spec:
      containers:
      - name: bun-app
        image: goodeesh/my-bun-app:local
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"  # Increase memory request
          limits:
            cpu: "500m"
            memory: "768Mi"    # Significantly increase memory limit
        ports:
        - containerPort: 5000
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          failureThreshold: 10
          periodSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 0
          periodSeconds: 2