apiVersion: v1
kind: Service
metadata:
  name: bun-app-service
spec:
  selector:
    app: bun-app
  ports:
  - protocol: TCP
    port: 5000 #this is the port where the service will run
    targetPort: 5000 # this is the port where the app runs
    nodePort: 31000
  type: NodePort
