apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: goodeesh/my-node-app:local
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "100m"  # Request 100 millicores
            memory: "128Mi"  # Request 128 MiB
          limits:
            cpu: "500m"  # Max 500 millicores
            memory: "256Mi"  # Max 256 MiB
        ports:
        - containerPort: 3000
