apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2  # Increase replicas
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      initContainers:
      - name: wait-for-postgres
        image: alpine
        command: ['sh', '-c', 'apk add --no-cache netcat-openbsd && until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: node-app
        image: goodeesh/my-node-app:local
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "1000m"
            memory: "1024Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DATABASE_URL
        ports:
        - containerPort: 3000
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 10
          periodSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 0
          periodSeconds: 2